version: "3.8"
services:

    docs:
        image: jekyll/jekyll:4.0.1
        ports:
            - 4000:4000
        volumes:
            - ./docs:/srv/jekyll
        command: jekyll serve --incremental
